config/routes.rb
CodeAndo::Application.routes.draw do

 root :to => 'bienvenidos#index'
 
 get "principal" => "bienvenidos#index", :as => "principal"
 
 get "registrarse" => "usuarios#new", :as => "registrarse"
 get "logueo" => "sesiones#new", :as => "logueo"
 get "logout" => "sesiones#destroy", :as => "logout"
 get "inicio" => "inicio#index", :as => "inicio"
 get "dat" => "personas#new", :as => "dat"

  resources :bienvenidos
  resources :sesiones
  resources :usuarios
  resources :inicio
  resources :personas

    

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  #Relaciones de las bases de datos
  belongs_to :usuario
  has_one :usuario

  #REGEX
  regex_entero = /^(?:\+|-)?\d+$/


  attr_accessible :apellidos, :cedula, :fecha_nacimiento, :nombres, :sexo, :usuario_id


  validates :nombres, :presence => {:message => " no puede estar en blanco"}
  validates :apellidos, :presence => {:message => " no puede estar en blanco"}
  validates :cedula, :presence => {:message => " no puede estar en blanco"}, :format => { :with => regex_entero, :message => " incorrecta solo puede contener numero entero"}, :length => {:is => 8, :message => "debe  contener 8 caracteres"}
  validates :fecha_nacimiento, :presence => {:message => " no puede estar en blanco"}
  validates :sexo, :presence => {:message => " No puede quedar en blanco"}


  before_save :convertir_minuscula

  def convertir_minuscula
    self.nombres = self.nombres.downcase
    self.apellidos = self.apellidos.downcase
    self.sexo = self.sexo.downcase
  end

  def verificar_entero
    unless regex_entero.match(cedula)
      nil 
    end
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  #Relaciones de las bases de datos
  has_one :persona
  belongs_to :persona

  #REGEX 
  regex_email = /^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/  
 
 
  attr_accessible :email, :password, :password_confirmation, :usuario, :persona_id 


  validates :usuario, :uniqueness => true,:presence => {:message => "no puede estar en blanco"}, :length => {:in => 5..20, :message => "debe copntener entre 5 y 20 caracteres"}

  validates :email, :uniqueness => true, :presence => { :case_sensitive => false, :message => "es incorrecto"}, :format => { :with => regex_email, :message => "El correo debe seguir el formate 'user@mail.com'" }

  validates :password, :presence => {:message => "no puede estar en blanco"}, :confirmation => {:message => " no coincide"}
  
  before_save :encriptar_password

  def encriptar_password
    if password.present?
      self.llave = BCrypt::Engine.generate_salt
      self.password = BCrypt::Engine.hash_secret(password, self.llave)
    end
  end

  def self.autenticar(_usuario, _password)
    user = Usuario.where("usuario = ?", _usuario).first 
    if user && user.password == BCrypt::Engine.hash_secret(_password, user.llave)
      user
    else
      nil
    end
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	def verifica_login(parametros = {})
		unless session[:usuario_id]
    		redirect_to parametros[:ruta], :notice => parametros[:mensaje]
    	else
    		redirect_to parametros[:ruta], :notice => parametros[:mensaje]
    	end
    end
end

app/controllers/bienvenidos_controller.rb
class BienvenidosController < ApplicationController
	
  
  	def index
  	end

end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  
  before_filter do |controlador|
    controlador.verifica_login :ruta => "/logueo", :existe_usuario => session[:usuario_id], :mensaje => "no has iniciado sesion aun mijo 'view inicio'"
  end

  def index
  	if session["usuario_id"]
  		@usuario = Usuario.find(session["usuario_id"])
  	end
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
 
  before_filter do |controlador|
      controlador.verifica_login :ruta =>"/logueo",:existe_usuario => session[:usuario_id], :mensaje => " no puedes xq no has iniciado sesion 'view personas'"
  end
  
  def new
  	@persona = Persona.new
  end

  def create
  	@persona = Persona.new(params[:persona])
  	if @persona.save
      
      temp = Usuario.find(@persona.usuario_id)
      temp.persona_id = @persona
      temp.save

  		redirect_to inicio_path, :notice => "Los Cambios han sido Guardados con Exito"
  	else
  		render 'new'
  	end
  end
end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController
    
    before_filter :only => [:new, :create] do |controlador|
        #Si existe el usuario lo compruebo
        if session[:usuario_id]  
          redirect_to "/inicio", :mensaje => "bienvenido has iniciado sesion con exito 'view sesiones'"
        end
    end
    
    def new
    end

    def create
        usuario = Usuario.autenticar(params[:usuario], params[:password])
        if usuario
      		session[:usuario_id] = usuario.id
      		redirect_to inicio_index_path, :notice => "Enhorabuena has iniciado sesion con EXITO..!!"
      	else
      		flash.now.alert = "Usuario o Password Invalido"
      		render 'new'
      	end
    end

    def destroy
        if session[:usuario_id]
            session[:usuario_id] = nil
            redirect_to "/logueo", :notice => "Has salido correctamente Vuelve Pronto..!!"
        else
            redirect_to "/logueo", :notice => "No has iniciado una sesion aun"
        end
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  
  before_filter do |controlador|
      if session[:usuario_id]
        redirect_to "/inicio", :mensaje => "no haz iniciado sesion 'view usuario'"
      
      end
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(params[:usuario])
    if @usuario.save
      redirect_to '/inicio'
    else
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bienvenidos/index.html.erb
<h1>Bienvenido a la pagina principal de nuestra Aplicacion</h1>

<h2>estamos en el controlador Bienvenidos</h2>

<%= link_to "registrarse", "/registrarse" %></br></br></br>
<%= link_to "Iniciar Sesion", "/logueo" %></br></br></br>

app/views/inicio/index.html.erb
<h1>bienvenido a la view inicio</h1>
<%=@usuario.to_json %>
<%= link_to "datos personales", dat_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeAndo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
    	<%= content_tag :div, msg, :id => "flash#{name}" %>
  	<% end %>

<%= yield %>

</body>
</html>

app/views/personas/create.html.erb
<h1>Personas#create</h1>
<p>Find me in app/views/personas/create.html.erb</p>

app/views/personas/new.html.erb
<h1>Bienvenido a tu Perfil</h1>
<h1>Termina de completar tu informacion personal</h1>

<%= form_for @persona do |f| %>
	<% if @persona.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
          <ul>
            <% for message in @persona.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
	<%end%>

  <!-- Le a#adi este campo para al momento de crear la persona ya se vaya con el id del usuario-->
  <input type="hidden" value="<%= session[:persona_id] %>" name= "persona[persona_id]">
	<p>
		<%= f.label :nombres %><br />
		<%= f.text_field :nombres %> 
	</p>
	<p>
		<%= f.label :apellidos %><br />
		<%= f.text_field :apellidos %> 
	</p>
	<p>
		<%= f.label :cedula %><br />
		<%= f.text_field :cedula %> 
	</p>
    <p>
      <%= f.label :sexo %><br />
      <%= f.text_field :sexo%>
    </p>
    <p>
      <%= f.label :fecha_nacimiento %><br />
      <%= f.date_select :fecha_nacimiento %>
    </p>
    <p class="button"><%= submit_tag "Guardar Cambios"%></p> 

<% end %>

app/views/sesiones/new.html.erb
<h1>Iniciar sesion</h1> 

<%= form_tag sesiones_path do %>
	<p>
		<%= label_tag :usuario %></br>
		<%= text_field_tag :usuario %>
	</p>
	<p>
		<%= label_tag :password %></br>
		<%= password_field_tag :password %>
	</p>

	<p class="button"><%= submit_tag "Iniciar sesion"%></p>  

<% end %>

 
 
  

app/views/usuarios/create.html.erb
<h1>Bienvenido a la view create de usuarios</h1>

app/views/usuarios/new.html.erb
<h1>Bienvenido</h1>


<h1>Registrarse</h1>

<%= form_for @usuario do |f| %>
    <% if @usuario.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @usuario.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :usuario %><br />
      <%= f.text_field :usuario %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>

    <p class="button"><%= submit_tag "Registrarse"%></p> 


<% end %>